### ISSUE TITLE
Verify token again after making a mistake

### ISSUE THREAD

**Issue by jordyvanraaij** [messagebird/messagebird-nodejs#34]
Why are you only able to use the ID in the verify object once when sending in a verify token? When a user makes a mistake in entering the token they need another verify object (thus .create) again in order to pass two-factor auth. Situation:

User is presented with number input and enters phone-number and clicks next
We use the verify.create() method to create a verify object based on the users phone-number
User receives and SMS with a token and enters the token
We use the ID generated by the verify object in step 1 and the token submitted by the user and verification fails because user entered wrong token
User can't re-enter the token because ID is already used

This is very weird and confusing for our users (and for all users of messagebird in general i assume). I can understand that you cannot allow 100 tries to validate the phone-number but give the user at least 3 tries to enter the correct code without expiring the verify ID.

Is this something that can be fixed? Or is there a neat way around this problem?

**Comment by marcelcorso** [comment]
Hey @jordyvanraaij ! 
Thanks for the thoughts. This sdk is just a wrapper for the API and not responsible for the actual inner workings of the API. 

If you have questions about the API itself reach out to MessageBird's support over here: https://support.messagebird.com/hc/en-us

About the issue you raised about the expiring tokens... It **probably** works like this for security reasons. I'm versed enough on security to have an opinion but if you are really interested please contact support and they will tell you the details.

Also there is a blog post about the api on the messagebird blog: https://blog.messagebird.com/verify-phone-numbers-a-developers-guide-ba6e3a54d5cc
 
I'm closing this because this issue not related to this SDK.
